#!/usr/bin/env bash

ALT_CURL=$1
UPDATE_WH=$2

USING_ALT_CURL=false
CURL_LOC=$(which curl)

if [[ $? -ne 0 ]]; then
    if [[ -z $ALT_CURL ]]; then
        echo "[ - ] Failed to locate cURL." 1>&2
        echo "[ - ] Make sure cURL is installed and available." 1>&2
        echo "[ - ] Alternatively, you may pass this script a valid location to a cURL binary as it's first argument." 1>&2
        exit 1
    fi

    if [[ $($ALT_CURL -V 2>/dev/null | grep -Eo "^curl") != "curl" ]]; then
        echo "[ - ] '${ALT_CURL}' is not a valid cURL binary." 1>&2
        exit 1
    fi

    CURL_LOC="${ALT_CURL}"
    USING_ALT_CURL=true
fi

if [[ -z $GIT_DIR ]]; then
    GIT_DIR=".git"
fi

# ensure we're inside a git repository.
if [[ $(find . -maxdepth 1 -type d -name $GIT_DIR -printf "%P" | tr -d "\n") != $GIT_DIR ]]; then
    echo "[ - ] No git directory found." 1>&2
    echo "[ - ] Make sure you're inside a git repository." 1>&2
    exit 1
fi

HOOKS_DIR=$(git config core.hooksPath)
if [[ -z $HOOKS_DIR ]]; then
    HOOKS_DIR=$GIT_DIR/hooks
fi

# ensure we have rw perms on the hooks dir.
if [[ ! -r $HOOKS_DIR ]] || [[ ! -w $HOOKS_DIR ]]; then
    echo "[ - ] Unable to access ${HOOKS_DIR}." 1>&2
    exit 1
fi

# preserve the current path just in case
PROJ_DIR=$(pwd)
RAW_URL="https://raw.githubusercontent.com/tins2831/git-notif/master/notifier.py"
CURL_OPTS="--silent --show-error"

cd $HOOKS_DIR
$CURL_LOC $CURL_OPTS --output post-commit $RAW_URL

EXIT_CODE_PRESERVED=$?
if [[ $EXIT_CODE_PRESERVED -ne 0 ]]; then
    echo "[ - ] cURL command failed." 1>&2
    exit $EXIT_CODE_PRESERVED
fi

chmod 755 post-commit

cd $PROJ_DIR

# if -u is the first command line arg then move it over to $UPDATE_WH.
if ! $USING_ALT_CURL && [[ -z $UPDATE_WH ]]; then
    if [[ ! -z $ALT_CURL ]]; then
        UPDATE_WH="${ALT_CURL}"
    fi
fi

# python3 is already installed, so use it to handle the installation of the
# config file instead of having the end-user install further dependencies
# like jq.
python3 -c '
import json
import sys
import os.path

newer_keys = {
    "include_diff": False
}

if os.path.exists(".wh_config.json"):
    config_fobj = open(".wh_config.json", "r")
    config_data = json.loads(config_fobj.read())
    config_updated = False

    config_fobj.close()

    missing = []
    for key in newer_keys.keys():
        if key in config_data:
            continue
        
        missing.append(key)

    if len(missing) > 0:
        for key in missing:
            config_data[key] = newer_keys[key]
        
        config_updated = True

    if len(sys.argv) >= 3 and sys.argv[2] in "-u|--update-webhook".split("|"):
        wh_url_split = sys.argv[1].split("/")

        config_data["wh_id"] = wh_url_split[-2]
        config_data["wh_token"] = wh_url_split[-1]

        print("[ + ] Updated config webhook details.")

    config_fobj = open(".wh_config.json", "w")

    config_fobj.write(json.dumps(config_data, indent = 2))
    config_fobj.close()

    if config_updated:
        print("[ + ] Config file updated.")
else:
    config_fobj = open(".wh_config.json", "w")
    config_data = {
        "wh_id": "",
        "wh_token": "",
        "wh_username": "",
        "wh_avatar_url": "",
        "include_diff": False
    }

    if len(sys.argv[1]) > 0:
        wh_url_split = sys.argv[1].split("/")

        config_data["wh_id"] = wh_url_split[-2]
        config_data["wh_token"] = wh_url_split[-1]

    config_fobj.write(json.dumps(config_data, indent = 2))
    config_fobj.close()
' $DISCORD_WH_URL $UPDATE_WH

EXIT_CODE_PRESERVED=$?
if [[ $EXIT_CODE_PRESERVED -ne 0 ]]; then
    echo "[ - ] Failed to set the config file." 1>&2
    exit $EXIT_CODE_PRESERVED
fi

echo "[ + ] Installed."
